// angular-client/src/app/app.ts
import { defer } from 'rxjs';

import { Component, model, OnDestroy, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatInputModule } from '@angular/material/input';
import { MatTableModule } from '@angular/material/table';
import { RouterOutlet } from '@angular/router';
import * as signalr from '@microsoft/signalr';

import { IMessageInfo } from '../data-types/IMessageInfo';

@Component({
  selector: 'app-root',
  imports: [
    FormsModule,
    MatButtonModule,
    MatInputModule,
    MatTableModule,
    RouterOutlet
  ],
  templateUrl: './app.html',
  styleUrl: './app.css'
})
export class App implements OnInit, OnDestroy {

  private chatConnection: signalr.HubConnection | null = null;

  protected readonly title = signal<string>('angular-client');

  public userName = model<string>('');
  public inputText = model<string>('');
  public messages = model<IMessageInfo[]>([]);

  public ngOnInit(): void {
    const connection = new signalr.HubConnectionBuilder()
      .withUrl('http://localhost:5180/chat')
      .withAutomaticReconnect()
      .build();

    this.chatConnection = connection;

    defer(() => connection.start())
      .subscribe({
        next: () => {
          connection.on('receivedMessage', (userName: string, message: string) => {
            console.log(`Message received from ${userName}: ${message}`);
            this.messages.update((prev) => [...prev, { userName, message }]);
          });
        },
        error: (e) => {
          console.error('Error connecting to SignalR hub:', e);
        }
      });
  }

  public ngOnDestroy(): void {
    this.chatConnection?.stop();
  }

  public sendMessage(): void {
    const connection = this.chatConnection;
    if (!!connection && connection.state === signalr.HubConnectionState.Connected && !!this.inputText().trim()) {
      defer(() => connection.send('sendMessage', this.userName(), this.inputText()))
        .subscribe({
          next: () => {
            this.inputText.set('');
          },
          error: (e) => {
            console.error('Error sending message:', e);
          },
        });
    }
  }

}

// react-client/src/App.tsx
import './App.css';

import React, { useEffect, useState } from 'react';
import { Button, Container, Form, InputGroup, Table } from 'react-bootstrap';

import * as signalr from '@microsoft/signalr';

import { IMessageInfo } from './data-types/IMessageInfo';

export default function App(): React.JSX.Element {

  const [connection, setConnection] = useState<signalr.HubConnection | null>(null);

  const [userName, setUserName] = useState<string>('');
  const [inputText, setInputText] = useState<string>('');
  const [messages, setMessages] = useState<IMessageInfo[]>([]);

  useEffect(() => {
    const chatConnection = new signalr.HubConnectionBuilder()
      .withUrl('http://localhost:5180/chat')
      .withAutomaticReconnect()
      .build();

    setConnection(chatConnection);

    chatConnection.start()
      .then(() => {
        console.log('Connected to SignalR hub');

        chatConnection.on('receivedMessage', (userName: string, message: string) => {
          console.log(`Message received from ${userName}: ${message}`);
          setMessages(prev => [...prev, { userName, message }]);
        });
      })
      .catch((error) => {
        console.error('Error connecting to SignalR hub:', error);
      });

    return (() => {
      chatConnection?.stop();
    });

  }, []);

  const handleSendMessage = async (): Promise<void> => {
    if ((connection?.state === signalr.HubConnectionState.Connected) && inputText.trim()) {
      await connection.send('sendMessage', userName, inputText);
      setInputText('');
    }
  };

  return (
    <>
      <Container>
        <InputGroup>
          <Form.Control
            placeholder='User name'
            value={userName}
            onChange={(e): void => setUserName(e.target.value)}
          />
          <Form.Control
            placeholder='Message'
            value={inputText}
            onChange={(e): void => setInputText(e.target.value)}
          />
          <Button onClick={handleSendMessage}>Send message</Button>
        </InputGroup>

        <Table hover striped>
          <thead>
            <tr>
              <th>User name</th>
              <th>Message</th>
            </tr>
          </thead>
          <tbody>
            {messages.map((message) => (
              <>
                <tr>
                  <td>{message.userName}</td>
                  <td>{message.message}</td>
                </tr>
              </>
            ))}
          </tbody>
        </Table>
      </Container>
    </>
  );

}
